name: GearWars
main: me.libraryaddict.gearwars.GearWars
author: libraryaddict
version: §fbuilt on §a24-10-2017 02:42
depend: [ProtocolLib, InventoryApi]
load: STARTUP
commands:
  forcestart:
    aliases: [fstart]
  time:
  goto: